// <auto-generated />
namespace MusicCat.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class thrid : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(thrid));
        
        string IMigrationMetadata.Id
        {
            get { return "202010291525402_thrid"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
